[package]
name = "mcw"
version = "1.2.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
serde = {version = "1.0.215", features = ["derive"]}
tokio = { version = "1.41.1", features = ["full"]}
toml = "0.8.19"
